package exceptiondemo;

public class Exceptiondemo01 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try{
		int a=50;
		int b=0;
		int c=a/b;
		System.out.println("the result is :"+c);
		}
		catch(ArithmeticException e){
			System.out.println("got some exception "+e.getMessage());
		}
	}

}
