package exceptiondemo;

public class Exceptiondemo01 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try{
			int c=0;
		int a=50;
		int[] b={1,2,5,10,10};
		for(int i=0;i<5;i++){
			c=a/b[i];
			System.out.println("the result is :"+c);
		}
		
		}
		catch(ArithmeticException e){
			e.printStackTrace();
		}
	}

}
